- name: Install asdf version manager
  unarchive:
    become: true
    src: https://github.com/asdf-vm/asdf/releases/download/v0.16.7/asdf-v0.16.7-linux-386.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  tags:
    - asdf

- name: Add asdf to oh-my-zsh plugins list
  replace:
    path: ~/.zshrc
    regexp: 'plugins=\((.*)\)'
    replace: 'plugins=(asdf \1)'
  tags:
    - asdf

- name: Install asdf golang plugin
  shell: '{{ asdf_executable }} plugin add golang https://github.com/asdf-community/asdf-golang.git'
  tags:
    - asdf

- name: Install asdf lazydocker plugin
  shell: '{{ asdf_executable }} plugin add lazydocker https://github.com/comdotlinux/asdf-lazydocker.git'
  tags:
    - asdf

- name: Install asdf neovim plugin
  shell: '{{ asdf_executable }} plugin add neovim https://github.com/richin13/asdf-neovim'
  tags:
    - asdf

- name: Install asdf nodejs plugin
  shell: '{{ asdf_executable }} plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git'
  tags:
    - asdf

- name: Install asdf python plugin
  shell: '{{ asdf_executable }} plugin add python https://github.com/asdf-community/asdf-python'
  tags:
    - asdf

- name: Install asdf rust plugin
  shell: '{{ asdf_executable }} plugin add rust https://github.com/code-lever/asdf-rust'
  tags:
    - asdf

- name: Install asdf tool versions
  shell: '{{ asdf_executable }} install'
  tags:
    - asdf-tools

- name: Set asdf tool versions globally
  copy:
    src: .tool-versions
    dest: ~/
  tags:
    - asdf-tools
